[package]
name = "ntp-client-sidecar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ntp-client-sidecar"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
chrono = "0.4"
